name: "{{project_name}}"
organisation: "{{organisation}}"
author: "{{author}}"
contact: "{{contact}}"
company: "{{company}}"
version: "0.0.1"
release: "0.0.1"
copyright_year: {{now.year}}
{% if project_type == '2'%}
command_line_interface: "{{cli}}"
entry_point: "{{project_name | replace('-', '_')}}.main:main"
{% endif %}
{% if project_type == '3'%}
external_module_library: {{project_name}}
sources:
{% for source in sources: %}
  - '{{source}}'
{% endfor %}
{% endif %}
license: {{license}}
dependencies:
  - update_your_dependencies_here>=0.4.4
description: "{{description}}"